CREATE TABLE IF NOT EXISTS presence (id TEXT PRIMARY KEY, name TEXT NOT NULL, seen INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS presence_seen ON presence (seen);
CREATE TABLE IF NOT EXISTS nutzung (tag TEXT NOT NULL, id TEXT NOT NULL, name TEXT NOT NULL, takte INTEGER NOT NULL DEFAULT 0, aktive INTEGER NOT NULL DEFAULT 0, erste INTEGER NOT NULL, letzte INTEGER NOT NULL, PRIMARY KEY (tag, id));
CREATE INDEX IF NOT EXISTS nutzung_tag ON nutzung (tag);
